=== peta/Uniform-API-Viewer/UAPID Specification/Schemata/UniformAPIDocumentation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    targetNamespace="http://www.petergeil.name/NS/UniformAPIDocumentation" version="0.1"
    xmlns:uad="http://www.petergeil.name/NS/UniformAPIDocumentation"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="directory">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="uad:document"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="document">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="metadata">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="documentTitles">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="short">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                  <xs:maxLength value="20"/>
                                                  <xs:whiteSpace value="collapse"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="full" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="website-url" type="xs:anyURI"/>
                            <xs:element name="description" type="xs:string"/>
                            <xs:element name="license" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:choice maxOccurs="unbounded" minOccurs="1">
                    <xs:element name="manual">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element maxOccurs="1" minOccurs="0" name="meta"
                                    type="uad:metaInformation"/>
                                <xs:group maxOccurs="unbounded" ref="uad:contentElement"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="group" type="uad:abstractApiElementContainer"> </xs:element>
                    <xs:element name="reference" type="uad:concreteApiElementContainer"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="repository-url" type="xs:anyURI"/>
            <xs:attribute form="unqualified" name="nsstring" type="xs:QName"/>
            <xs:attribute name="version" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="abstractApiElementContainer">
        <xs:sequence>
            <xs:group maxOccurs="unbounded" ref="uad:apiElement"/>
            <xs:element name="group" type="uad:abstractApiElementContainer"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="concreteApiElementContainer">
        <xs:sequence>
            <xs:group maxOccurs="unbounded" ref="uad:apiElement"/>
        </xs:sequence>
        <xs:attribute name="nature" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="module"/>
                    <xs:enumeration value="plugin"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType mixed="false" name="rawSourceCode">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="embedInSandbox"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="metaInformation">
        <xs:sequence>
            <xs:element minOccurs="0" name="title" type="xs:string"/>
            <xs:element minOccurs="0" name="author" type="xs:string"/>
            <xs:element minOccurs="0" name="description" type="xs:string"/>
            <xs:element minOccurs="0" name="tagList" type="xs:string"/>
            <xs:element minOccurs="0" name="webUrl" type="xs:anyURI"/>
        </xs:sequence>
    </xs:complexType>
    <xs:group name="contentElement">
        <xs:choice>
            <xs:element name="html" type="xs:string"/>
            <xs:element name="code" type="uad:rawSourceCode"/>
            <xs:element name="paragraph" type="xs:string"/>
            <xs:element name="declaration" type="xs:string"/>
            <xs:element name="headline" type="xs:string"/>
        </xs:choice>
    </xs:group>
    <xs:group name="apiElement">
        <xs:choice>
            <xs:element name="package" type="uad:packageDef"/>
            <xs:element name="class" type="uad:classDef"/>
            <xs:element name="function" type="uad:functionDef"/>
            <xs:element name="property" type="uad:propertyDef"/>
        </xs:choice>
    </xs:group>
    <xs:complexType name="functionDef">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="paramsDef" type="uad:functionParamsDef"/>
            <xs:element minOccurs="0" name="modifiers" type="uad:apiElemModifierEnums"/>
            <xs:element default="void" name="typeOfReturnValue" type="xs:string"/>
            <xs:element name="documentation" type="uad:apiElemDocumentation"/>
        </xs:sequence>
        <xs:attributeGroup ref="uad:apiElemIndentifier"/>
    </xs:complexType>
    <xs:complexType name="classDef">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="constructorParamsDef" type="uad:functionParamsDef"/>
            <xs:element name="inheritsFrom">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="className"
                            type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="classMethods">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="method" type="uad:functionDef"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="documentation" type="uad:apiElemDocumentation"/>
        </xs:sequence>
        <xs:attributeGroup ref="uad:apiElemIndentifier"/>
    </xs:complexType>
    <xs:complexType name="propertyDef">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="classOf" type="xs:string"/>
            <xs:element minOccurs="0" name="modifiers" type="uad:apiElemModifierEnums"/>
            <xs:element name="documentation" type="uad:apiElemDocumentation"/>
        </xs:sequence>
        <xs:attributeGroup ref="uad:apiElemIndentifier"/>
    </xs:complexType>
    <xs:complexType name="packageDef">
        <xs:choice maxOccurs="unbounded" minOccurs="1">
            <xs:element name="class" type="uad:classDef"/>
            <xs:element name="function" type="uad:functionDef"/>
            <xs:element name="property" type="uad:propertyDef"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="functionParamsDef"> </xs:complexType>
    <xs:complexType name="apiElemDocumentation">
        <xs:group maxOccurs="unbounded" ref="uad:contentElement"/>
    </xs:complexType>
    <xs:complexType name="apiElemModifierEnums">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="modifier">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="static"/>
                        <xs:enumeration value="final"/>
                        <xs:enumeration value="virtual"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:attributeGroup name="apiElemIndentifier">
        <xs:attribute id="apiElemId" name="uri"/>
    </xs:attributeGroup>
</xs:schema>

=== peta/Uniform-API-Viewer/UAPID Specification/Sample Files/sample_instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<directory xmlns="http://www.petergeil.name/NS/UniformAPIDocumentation"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.petergeil.name/NS/UniformAPIDocumentation file:/Volumes/Data/Work/Development/Uniform-API-Viewer/UAPID%20Specification/Schemata/UniformAPIDocumentation.xsd">
    <document>
        <metadata>
            <documentTitles>
                <short>short0</short>
                <full>full0</full>
            </documentTitles>
            <author>author0</author>
            <website-url>http://www.oxygenxml.com/</website-url>
            <description>description0</description>
            <license>license0</license>
        </metadata>
            <manual>
                    <headline>headline0</headline>
                    <headline>headline1</headline>
            </manual>
            <manual>
                    <declaration>declaration0</declaration>
                    <html>html0</html>
            </manual>
    </document>
    <document>
        <metadata>
            <documentTitles>
                <short>short1</short>
                <full>full1</full>
            </documentTitles>
            <author>author1</author>
            <website-url>http://www.oxygenxml.com/</website-url>
            <description>description1</description>
            <license>license1</license>
        </metadata>
            <reference nature="module">
                    <package>
                        <function>
                            <name>name0</name>
                            <paramsDef/>
                            <typeOfReturnValue>void</typeOfReturnValue>
                            <documentation>
                                <code>code0</code>
                                <code>code1</code>
                            </documentation>
                        </function>
                        <property>
                            <name>name1</name>
                            <classOf>classOf0</classOf>
                            <documentation>
                                <html>html1</html>
                                <paragraph>paragraph0</paragraph>
                            </documentation>
                        </property>
                    </package>
                    <property>
                        <name>name2</name>
                        <classOf>classOf1</classOf>
                        <documentation>
                            <paragraph>paragraph1</paragraph>
                            <headline>headline2</headline>
                        </documentation>
                    </property>
            </reference>
            <manual>
                    <code>code2</code>
                    <declaration>declaration1</declaration>
            </manual>
    </document>
</directory>
